### ISSUE TITLE
Two Adhearsion::Drb::Plugin::Service tests failing

### ISSUE THREAD

**Issue by jsgoecke** [adhearsion/adhearsion-drb#1]
1) Adhearsion::Drb::Plugin::Service while running the Drb service should return normal Ruby data structures properly over DRb
     Failure/Error: Adhearsion::Plugin.load
     NoMethodError:
       private method `load' called for Adhearsion::Plugin:Class
     # ./spec/adhearsion/drb/plugin/service_spec.rb:112:in`block (3 levels) in <top (required)>'

  2) Adhearsion::Drb::Plugin::Service while running the Drb service should raise an exception for a non-existent interface
     Failure/Error: Adhearsion::Plugin.load
     NoMethodError:
       private method `load' called for Adhearsion::Plugin:Class
     # ./spec/adhearsion/drb/plugin/service_spec.rb:112:in`block (3 levels) in <top (required)>'

**Comment by bklang** [comment]
Fixed and added to CI: https://ci.mojolingo.com/job/adhearsion-drb/
